name: GitHub Metrics Professional
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 📊 Profile Stats & Languages
        uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: stats-and-languages.svg
          base: header, community, repositories, metadata
          base_indepth: yes
          config_timezone: America/Lima
          
          # Lenguajes: Forzamos la aparición de tus stacks principales
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_languages_recent_days: 0

      - name: 🔥 Coding Activity (Habits)
        uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: habits.svg
          base: ""
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: yes
          plugin_habits_charts: yes
